export const categories = ["Caixa","Oferta","Criativo","Funil","Diagnóstico","Validação","Escala"] as const;
export type Category = typeof categories[number];
export type Difficulty = "Treino" | "Operador" | "Estrategista";
export type Question = {
  id:number; category:Category; difficulty:Difficulty; title:string; context:string;
  options:string[]; correct:number; explanation:string; keyNumber:string; nextStep:string;
};

export const questions: Question[] = [
{ id:1,category:"Caixa",difficulty:"Treino",title:"Você começa com R$600. Qual é a primeira regra?",context:"Você ainda não validou a oferta e precisa testar aquisição sem comprometer sua operação.",options:["Investir todo o caixa no primeiro teste","Definir um limite de perda no teste","Comprar ferramentas antes de medir","Subir o preço antes de validar"],correct:1,explanation:"Antes de buscar volume, preserve runway. Caixa compra tempo para aprender.",keyNumber:"R$600",nextStep:"Defina um teto de perda para o teste e acompanhe o retorno."},
{ id:2,category:"Oferta",difficulty:"Treino",title:"A oferta parece confusa. O que corrigir primeiro?",context:"As pessoas entendem o produto, mas não conseguem explicar claramente por que deveriam comprar.",options:["Trocar a plataforma de aquisição","Simplificar promessa e mecanismo","Produzir mais peças para testar","Aumentar a verba da campanha"],correct:1,explanation:"Uma oferta precisa ser compreendida antes de ser escalada.",keyNumber:"Clareza",nextStep:"Escreva uma promessa específica e o mecanismo que entrega essa transformação."},
{ id:3,category:"Criativo",difficulty:"Treino",title:"O CTR caiu, mas o checkout continua normal.",context:"A página e o pagamento não apresentaram mudanças. O anúncio perdeu capacidade de gerar cliques.",options:["Revisar a etapa de pagamento","Investigar fadiga e renovar ângulos","Trocar o produto neste momento","Aumentar a verba da campanha"],correct:1,explanation:"Se o restante do funil está estável e o CTR cai, o criativo é um suspeito forte.",keyNumber:"CTR",nextStep:"Teste novos hooks e ângulos mantendo o restante constante."},
{ id:4,category:"Funil",difficulty:"Operador",title:"Muita gente chega ao checkout, mas poucas compram.",context:"O anúncio gera tráfego e a página convence, porém a conversão final está baixa.",options:["Publicar mais conteúdo orgânico","Auditar preço, confiança e pagamento","Aumentar o custo de aquisição","Trocar elementos da identidade"],correct:1,explanation:"O gargalo está perto da conversão. Não faz sentido escalar tráfego antes de corrigir o vazamento.",keyNumber:"Checkout",nextStep:"Compare início de checkout, pagamento iniciado e pagamento aprovado."},
{ id:5,category:"Diagnóstico",difficulty:"Operador",title:"Você quer mudar tudo porque o resultado caiu.",context:"Oferta, criativo e público foram alterados recentemente e agora você não sabe o que causou a queda.",options:["Alterar várias partes novamente","Mudar uma variável por vez","Parar tudo sem analisar dados","Aumentar a verba para compensar"],correct:1,explanation:"Quando muitas variáveis mudam juntas, você perde a capacidade de atribuir causa.",keyNumber:"1 variável",nextStep:"Escolha a hipótese mais provável e teste isoladamente."},
{ id:6,category:"Validação",difficulty:"Treino",title:"Uma venda significa que o produto foi validado?",context:"Seu primeiro teste gerou uma compra e você está pensando em aumentar bastante o investimento.",options:["Uma venda já confirma a oferta","Uma venda ainda é sinal inicial","Muitos cliques já validam a oferta","Preço baixo facilita a validação"],correct:1,explanation:"Uma venda mostra que é possível vender. Validação exige repetição com economia saudável.",keyNumber:"1 venda",nextStep:"Busque repetição do resultado em mais de uma oportunidade."},
{ id:7,category:"Escala",difficulty:"Operador",title:"Quando faz sentido aumentar o investimento?",context:"A campanha apresenta ROI saudável por vários ciclos e você entende o que está funcionando.",options:["Após a primeira venda","Com consistência e margem saudável","Quando houver pressão para crescer","Antes de conhecer o CPA"],correct:1,explanation:"Escala deve ampliar algo que já funciona, não tentar descobrir se funciona.",keyNumber:"Consistência",nextStep:"Aumente gradualmente e monitore CPA, margem e ROI."},
{ id:8,category:"Caixa",difficulty:"Operador",title:"Você vende, mas o caixa está diminuindo.",context:"Existe faturamento, porém gastos de aquisição e operação consomem o dinheiro disponível.",options:["Ignorar enquanto houver faturamento","Separar receita, margem, gastos e caixa","Escalar para aumentar o volume","Parar de registrar as despesas"],correct:1,explanation:"Faturamento não é caixa livre. O operador precisa enxergar a economia completa.",keyNumber:"Caixa",nextStep:"Monte um fluxo simples de entradas, saídas e caixa comprometido."},
{ id:9,category:"Oferta",difficulty:"Treino",title:"O anúncio promete uma coisa e a página outra.",context:"O criativo fala de um resultado específico, mas a landing page abre com uma mensagem genérica.",options:["Manter as mensagens diferentes","Alinhar a promessa do anúncio e página","Alterar somente o botão","Aumentar o preço da oferta"],correct:1,explanation:"A quebra de expectativa destrói confiança e conversão.",keyNumber:"Mensagem",nextStep:"Faça a pessoa reconhecer na página a mesma promessa que a trouxe até ali."},
{ id:10,category:"Criativo",difficulty:"Operador",title:"Você criou 10 criativos, mas todos parecem iguais.",context:"Só mudam cor, fonte e pequenos detalhes. O desempenho não muda.",options:["Criar outras variações visuais","Mudar ângulos, hooks, dores e provas","Aumentar a verba da campanha","Trocar a etapa de pagamento"],correct:1,explanation:"Dez versões cosméticas não são dez hipóteses.",keyNumber:"Ângulos",nextStep:"Crie variações que testem ideias diferentes, não apenas estética."},
{ id:11,category:"Funil",difficulty:"Operador",title:"Muitos Pix são gerados, poucos são pagos.",context:"O usuário demonstra intenção de compra, mas existe uma grande diferença entre Pix criado e Pix aprovado.",options:["Aumentar o tráfego da campanha","Investigar a etapa entre gerar e pagar","Trocar todo o público","Excluir quem não pagou"],correct:1,explanation:"O gargalo está na etapa de pagamento, não necessariamente na geração de demanda.",keyNumber:"Pix pago",nextStep:"Investigue prazo, confiança, instruções e recuperação de pagamentos."},
{ id:12,category:"Diagnóstico",difficulty:"Estrategista",title:"Qual métrica olhar primeiro quando as vendas caem?",context:"Você precisa descobrir em qual trecho do sistema o resultado começou a piorar.",options:["Olhar apenas o faturamento","Seguir o funil até achar a ruptura","Ver primeiro o número de seguidores","Usar curtidas como sinal principal"],correct:1,explanation:"Diagnóstico começa localizando o ponto de ruptura do funil.",keyNumber:"Gargalo",nextStep:"Compare o período atual com uma referência e encontre a primeira mudança relevante."},
{ id:13,category:"Validação",difficulty:"Operador",title:"O teste ainda não atingiu seu corte.",context:"Você definiu um limite de dados antes de decidir, mas ficou impaciente com um resultado parcial.",options:["Encerrar o teste neste momento","Respeitar o critério definido","Escalar para obter resposta rápida","Trocar oferta e público agora"],correct:1,explanation:"Um teste precisa de critério antes de você conhecer o resultado.",keyNumber:"Cutoff",nextStep:"Defina antecipadamente o que fará você continuar, ajustar ou parar."},
{ id:14,category:"Escala",difficulty:"Estrategista",title:"ROI 3+ aparece com consistência. Próximo passo?",context:"O resultado positivo se repete e o funil está operacional.",options:["Multiplicar a verba por dez","Escalar aos poucos e preservar margem","Parar após a validação","Trocar o criativo vencedor agora"],correct:1,explanation:"A escala responsável protege o que foi aprendido.",keyNumber:"ROI 3+",nextStep:"Aumente em degraus e confirme que CPA e margem continuam saudáveis."},
{ id:15,category:"Diagnóstico",difficulty:"Estrategista",title:"Ao escalar, o ROI piorou muito.",context:"A campanha era saudável em menor volume e perdeu eficiência após o aumento.",options:["Continuar aumentando a verba","Voltar ao ponto saudável e investigar","Trocar o produto sem investigar","Ignorar a queda do ROI"],correct:1,explanation:"Escala pode revelar limites de audiência, criativo ou economia.",keyNumber:"ROI",nextStep:"Reverta parcialmente a escala e identifique o novo gargalo."},
{ id:16,category:"Criativo",difficulty:"Operador",title:"CTR caiu enquanto checkout e conversão permanecem normais.",context:"A oferta ainda converte quem chega, mas o anúncio está trazendo menos pessoas.",options:["Reescrever o checkout da campanha","Testar novos hooks mantendo a oferta","Mudar o preço do produto","Trocar o produto neste momento"],correct:1,explanation:"O problema aparente está antes do clique.",keyNumber:"CTR",nextStep:"Preserve a oferta vencedora e renove a entrada do funil."},
{ id:17,category:"Oferta",difficulty:"Treino",title:"A oferta é bonita, mas ninguém entende.",context:"A página tem design sofisticado, porém usuários não conseguem explicar o que recebem.",options:["Adicionar mais elementos visuais","Simplificar a proposta até ficar clara","Colocar mais provas úteis","Aumentar o preço do produto"],correct:1,explanation:"Design apoia a oferta; não substitui clareza.",keyNumber:"Óbvia",nextStep:"Teste a proposta com alguém e veja se consegue repetir o que é vendido."},
{ id:18,category:"Criativo",difficulty:"Operador",title:"Todos os criativos usam o mesmo hook.",context:"Você quer volume de testes, mas todas as peças começam com a mesma ideia.",options:["Tratar os criativos como testes","Criar hooks com hipóteses diferentes","Duplicar a campanha atual","Aumentar o orçamento diário"],correct:1,explanation:"O aprendizado vem da diversidade de hipóteses.",keyNumber:"Hooks",nextStep:"Teste dor, desejo, mecanismo, prova, objeção e contraste."},
{ id:19,category:"Funil",difficulty:"Operador",title:"A página converte, o checkout não.",context:"A pessoa demonstra interesse e chega ao checkout, mas a etapa final despenca.",options:["Trocar o anúncio da campanha","Otimizar confiança e experiência final","Criar mais conteúdo para atrair","Aumentar o custo de aquisição"],correct:1,explanation:"Você deve atacar o trecho que está vazando.",keyNumber:"Checkout",nextStep:"Reduza fricção e verifique preço, meios de pagamento e confiança."},
{ id:20,category:"Caixa",difficulty:"Estrategista",title:"Você tem R$600 e quer testar 10 criativos.",context:"Seu orçamento é pequeno e cada teste consome parte relevante do caixa.",options:["Dividir a verba entre dez testes","Priorizar hipóteses e guardar caixa","Gastar tudo no primeiro dia","Comprar uma ferramenta para testar"],correct:1,explanation:"Com pouco caixa, concentração inteligente aumenta a chance de aprendizado útil.",keyNumber:"Reserva",nextStep:"Defina orçamento por hipótese e uma reserva que não será tocada."},
{ id:21,category:"Oferta",difficulty:"Operador",title:"O upsell não tem relação com a compra principal.",context:"Você tenta aumentar ticket, mas o produto adicional parece aleatório.",options:["Manter porque aumenta o ticket","Criar complemento ligado à compra","Colocar vários upsells no checkout","Baixar o preço do produto principal"],correct:1,explanation:"Um bom upsell resolve o próximo problema natural do cliente.",keyNumber:"Relevância",nextStep:"Mapeie o próximo passo que o comprador provavelmente precisa."},
{ id:22,category:"Validação",difficulty:"Estrategista",title:"Você quer mudar o público antes do cutoff.",context:"O teste está inconclusivo e você suspeita que outro público seria melhor.",options:["Mudar agora e encerrar o teste","Esperar o critério ou evidência forte","Mudar oferta e público ao mesmo tempo","Escalar para testar mais rápido"],correct:1,explanation:"Trocar a hipótese antes de medir destrói a leitura do experimento.",keyNumber:"Hipótese",nextStep:"Finalize o teste ou documente uma razão objetiva para interrompê-lo."},
{ id:23,category:"Validação",difficulty:"Estrategista",title:"Um criativo teve ROI 4,8 em um único dia.",context:"O resultado é excelente, mas ainda existe pouca amostra.",options:["Escalar dez vezes imediatamente","Tratar como sinal e buscar repetição","Declarar a oferta validada hoje","Trocar o criativo antes de saturar"],correct:1,explanation:"Um dia pode revelar potencial, mas consistência transforma sinal em confiança.",keyNumber:"4,8",nextStep:"Reproduza o desempenho antes de aumentar agressivamente."},
{ id:24,category:"Caixa",difficulty:"Estrategista",title:"Você vende, mas não consegue reinvestir.",context:"O faturamento cresce, porém custos e compromissos consomem o dinheiro.",options:["Tratar faturamento como lucro","Separar receita, custos, lucro e caixa","Aumentar tráfego para gerar volume","Parar de acompanhar os custos"],correct:1,explanation:"Crescimento sem caixa pode quebrar uma operação que parece saudável.",keyNumber:"Reinvestimento",nextStep:"Defina quanto da margem pode voltar para aquisição."},
{ id:25,category:"Diagnóstico",difficulty:"Estrategista",title:"O clique está barato, mas a venda está cara.",context:"O anúncio gera CPC baixo, mas poucas pessoas compram.",options:["Comemorar o CPC e escalar","Investigar onde o clique não converte","Trocar somente o anúncio","Aumentar o custo por clique"],correct:1,explanation:"CPC barato não paga as contas; a métrica final precisa fechar a economia.",keyNumber:"CPA",nextStep:"Localize onde a intenção se perde depois do clique."},
{ id:26,category:"Oferta",difficulty:"Estrategista",title:"O concorrente ficou mais barato.",context:"Você pensa em cortar preço imediatamente para acompanhar.",options:["Copiar imediatamente o preço","Comunicar valor antes de reduzir","Aumentar bastante o preço","Ignorar a mudança do concorrente"],correct:1,explanation:"Preço é uma alavanca, mas não deve ser a primeira resposta se existe valor não comunicado.",keyNumber:"Valor",nextStep:"Identifique o motivo concreto para escolher sua oferta."},
{ id:27,category:"Criativo",difficulty:"Operador",title:"Hook forte, vendas fracas.",context:"O anúncio consegue gerar cliques, mas a promessa não se sustenta na oferta.",options:["Aumentar a verba da campanha","Alinhar hook, promessa e oferta","Trocar apenas a imagem principal","Buscar ainda mais cliques"],correct:1,explanation:"A atenção pode estar funcionando enquanto a expectativa criada está errada.",keyNumber:"Alinhamento",nextStep:"Faça o criativo pré-vender exatamente a transformação que a oferta entrega."},
{ id:28,category:"Diagnóstico",difficulty:"Estrategista",title:"CTR subiu, CPC caiu, mas CPA piorou.",context:"As métricas do anúncio parecem melhores, porém o custo por venda aumentou.",options:["Escalar porque o CPC caiu","Seguir o funil até achar a perda","Ignorar o CPA por enquanto","Trocar todas as variáveis"],correct:1,explanation:"Métricas intermediárias melhores não garantem uma economia final melhor.",keyNumber:"CPA",nextStep:"Compare taxa de conversão pós-clique e valor por compra."},
{ id:29,category:"Validação",difficulty:"Estrategista",title:"Você quer validar cinco produtos com pouco caixa.",context:"Cada produto precisa de verba e você não terá dados suficientes se fragmentar demais.",options:["Testar os cinco produtos juntos","Priorizar a melhor hipótese e testar","Gastar tudo no produto mais caro","Escolher um produto por sorte"],correct:1,explanation:"Pouco capital exige priorização para gerar aprendizado com profundidade.",keyNumber:"Prioridade",nextStep:"Ordene hipóteses por potencial, custo de teste e evidência disponível."},
{ id:30,category:"Escala",difficulty:"Estrategista",title:"Você quer escalar porque está ansioso.",context:"Ainda não há evidência suficiente, mas a vontade de crescer está pressionando a decisão.",options:["Escalar para aliviar a ansiedade","Esperar evidência e proteger o caixa","Aumentar a verba em cinco vezes","Mudar a oferta sem novos dados"],correct:1,explanation:"Escala é decisão econômica, não emocional.",keyNumber:"Evidência",nextStep:"Volte aos critérios objetivos de validação antes de aumentar risco."},
];