export type Difficulty = "EASY"|"NORMAL"|"HARD"|"EXPERT"|"NIGHTMARE";
export type ScenarioCategory = "Oferta"|"Criativo"|"Métricas"|"Funil"|"Caixa"|"Escala"|"Recorrência";
export type Decision = {
  id:string; label:string; hint:string; correct?:boolean; cashDelta:number;
  xp:number; explanation:string; principle:string; consequence:string;
  metric?:string;
};
export type ScenarioMetrics = {
  cash:number; ticket:number; spend:number; impressions:number; clicks:number; ctr:number;
  cpc:number; checkout:number; pix:number; paid:number; sales:number; revenue:number; cpa:number; roi:number;
  days:number; creatives:number;
};
export type Scenario = {
  id:string; level:number; difficulty:Difficulty; category:ScenarioCategory; title:string; context:string;
  product:string; offer:string; metrics:ScenarioMetrics; available:string[]; hidden:string[];
  decisions:Decision[]; principle:string; xp:number; caseNote?:string; tags:string[];
};

const v=(n:number)=>n;
const metric=(ticket:number,spend:number,impressions:number,clicks:number,checkout:number,pix:number,paid:number,days:number,creatives:number):ScenarioMetrics=>{
  const ctr=impressions?clicks/impressions:0,cpc=clicks?spend/clicks:0,sales=paid,revenue=sales*ticket,cpa=sales?spend/sales:0,roi=spend?revenue/spend:0;
  return {cash:0,ticket,spend,impressions,clicks,ctr,cpc,checkout,pix,paid,sales,revenue,cpa,roi,days,creatives};
};

type Template={
 category:ScenarioCategory; level:number; difficulty:Difficulty; title:string; context:string;
 product:string; offer:string; build:(i:number)=>ScenarioMetrics; principle:string;
 correct:string; alternatives:[string,string,string]; explanations:[string,string,string,string]; tags:string[];
};

const templates:Template[]=[
{category:"Oferta",level:4,difficulty:"NORMAL",title:"Clique existe. Desejo, não.",context:"O anúncio chama atenção e a página recebe tráfego qualificado, mas quase ninguém avança. Antes de comprar mais mídia, você precisa descobrir se a proposta faz sentido.",product:"Mini-curso de vendas",offer:"R$ {t} com bônus e garantia",build:i=>metric([19.9,37.9,67,97,147][i], [28,46,72,105,138][i], [4200,5100,6400,7800,9100][i], [74,104,128,151,177][i], [4,6,8,9,11][i], [2,3,4,5,6][i], [0,1,1,1,1][i], [1,2,2,3,3], [2,3,3,4,5]),principle:"Diagnostique a oferta antes de comprar mais tráfego.",correct:"Revisar promessa, mecanismo, prova e congruência da oferta.",alternatives:["Aumentar orçamento para gerar mais volume.","Trocar o checkout sem evidência de abandono.","Criar dez anúncios novos imediatamente."],explanations:["Você tratou falta de desejo como falta de volume. O gargalo aparece depois do clique.","Você aumentou exposição sem resolver a proposta. Isso compra mais visitas para o mesmo vazamento.","Você mexeu no checkout sem evidência de que ele era o problema.","A leitura racional começa na oferta: tráfego já chega, mas a proposta não converte."] ,tags:["promessa","congruência","oferta"]},
{category:"Criativo",level:5,difficulty:"NORMAL",title:"O anúncio parou de abrir portas",context:"A campanha ainda entrega, mas a taxa de cliques caiu enquanto CPM ficou relativamente estável. O problema mais provável precisa ser separado de problemas de página.",product:"Workshop de anúncios",offer:"R$ {t} com aula prática",build:i=>metric([47,67,97,147,197][i],[32,51,74,112,145][i],[9000,11000,14000,17500,21000][i],[72,83,91,105,116][i],[7,8,9,11,12][i],[4,4,5,6,6][i],[1,1,1,2,2][i], [2,3,3,4,4][i],[3,4,5,6,8][i]),principle:"CTR é um sinal do anúncio, mas sempre leia junto do contexto.",correct:"Testar novo hook/ângulo mantendo a oferta sob controle.",alternatives:["Escalar orçamento porque ainda há impressões.","Reescrever o checkout imediatamente.","Mudar o preço sem investigar o anúncio."],explanations:["Você ignorou a perda de atenção. O volume de impressões não corrige um criativo cansado.","Escalar aumenta exposição, mas não resolve uma peça que perdeu capacidade de gerar clique.","Preço pode importar, mas não é a primeira evidência neste funil.","CTR caiu com entrega ainda presente: renovar o ângulo é um teste coerente."] ,tags:["hook","ângulo","fadiga"]},
{category:"Métricas",level:2,difficulty:"EASY",title:"O número que falta",context:"Você recebeu apenas ticket, gasto, vendas e CPA. A campanha parece boa, mas há informação demais faltando para decidir com segurança.",product:"Ebook de carreira",offer:"R$ {t}",build:i=>metric([19.9,37.9,67,97,147][i],[18,29,45,61,83][i],[0,0,0,0,0][i],[0,0,0,0,0][i],[0,0,0,0,0][i],[0,0,0,0,0][i],[1,1,1,1,1][i],1,1),principle:"Não tome decisão sem contexto suficiente.",correct:"Pedir CTR, CPC e dados do funil antes de decidir.",alternatives:["Escalar porque o CPA está abaixo do ticket.","Cortar imediatamente porque houve só uma venda.","Trocar o criativo sem olhar entrega."],explanations:["CPA isolado não informa como a venda aconteceu nem se existe escala sustentável.","Uma venda pode ser ruído. O contexto de volume e funil importa.","Trocar criativo sem evidência é mudança por achismo.","Você identificou a lacuna certa: pedir dados antes de alterar a operação."] ,tags:["contexto","diagnóstico","dados"]},
{category:"Funil",level:9,difficulty:"NORMAL",title:"O dinheiro está depois do checkout",context:"O anúncio tem clique, a página gera checkout e Pix, mas a taxa de pagamento despencou. O tráfego não é automaticamente o culpado.",product:"Curso de inglês",offer:"R$ {t} em pagamento único",build:i=>metric([37.9,67,97,147,197][i],[44,68,91,125,171][i],[7000,8800,10200,13000,16000][i],[126,158,184,221,256][i],[18,25,31,37,43][i],[15,21,27,32,39][i],[4,6,6,7,8][i],[2,2,3,3,4],[4,5,5,6,7]),principle:"Quando o Pix é gerado e não pago, investigue a etapa final.",correct:"Investigar preço, confiança, congruência e pagamento.",alternatives:["Trocar todos os criativos.","Dobrar o orçamento.","Desligar a campanha sem investigar o pagamento."],explanations:["O tráfego já chegou ao ponto de gerar Pix. Trocar criativos pode destruir uma parte saudável do funil.","Mais tráfego não corrige uma baixa taxa de pagamento.","Pausar pode proteger caixa, mas sem diagnóstico você perde a chance de saber a causa.","A queda está entre Pix gerado e Pix pago; essa etapa merece investigação."] ,tags:["pix","pagamento","checkout"]},
{category:"Caixa",level:1,difficulty:"EASY",title:"R$600 não é verba infinita",context:"Você tem caixa curto e uma oferta ainda não validada. O objetivo do primeiro teste é comprar aprendizado sem transformar o caixa em uma aposta.",product:"Template de produtividade",offer:"R$ {t}",build:i=>metric([19.9,37.9,67,97,147][i],[20,35,50,70,95][i],[5000,6500,8000,10000,12000][i],[90,105,120,135,150][i],[8,9,10,11,12][i],[5,6,7,8,9][i],[1,1,1,1,1][i],1,2),principle:"Caixa compra tempo para aprender.",correct:"Definir limite de perda e preservar runway.",alternatives:["Gastar todo o caixa no primeiro dia.","Comprar ferramentas antes de validar.","Aumentar orçamento após qualquer venda."],explanations:["Você colocou sobrevivência em risco antes de ter evidência.","Ferramenta não substitui validação.","Uma venda isolada não prova consistência.","Limite de perda preserva capacidade de testar de novo."] ,tags:["runway","risco","teste"]},
{category:"Escala",level:12,difficulty:"HARD",title:"Você está prestes a escalar um problema",context:"Ontem houve vendas e o ROI chamou atenção. Hoje o CPA subiu e o volume ainda é pequeno. A decisão precisa considerar consistência, não apenas o melhor dia.",product:"Mentoria de vendas",offer:"R$ {t}",build:i=>metric([97,147,197,297,497][i],[55,82,121,170,245][i],[12000,15000,19000,23000,28000][i],[170,201,230,268,302][i],[17,21,25,30,34][i],[13,16,19,22,25][i],[2,2,2,3,3][i],[2,2,3,3,4],[5,6,7,8,9]),principle:"Validação vem antes da escala.",correct:"Manter controlado e comprar evidência de consistência.",alternatives:["Aumentar orçamento em 100%.","Criar uma campanha paralela maior imediatamente.","Escalar porque o ROI de ontem foi alto."],explanations:["Você duplicou exposição sem provar estabilidade.","Mais campanhas aumentam variáveis antes de existir base.","Um pico isolado não é uma máquina validada.","A decisão fria é manter controle, observar CPA e gerar mais evidência."] ,tags:["validação","consistência","escala"]},
{category:"Métricas",level:11,difficulty:"HARD",title:"Nível da campanha",context:"A operação tem dados suficientes para classificar o momento atual. O ranking não é um botão automático: serve para orientar a intensidade da próxima decisão.",product:"Comunidade paga",offer:"R$ {t}/mês",build:i=>metric([47,97,147,197,297][i],[60,90,130,160,220][i],[10000,14000,18000,22000,26000][i],[160,220,270,330,380][i],[20,29,35,42,48][i],[15,22,28,34,40][i],[5,7,8,8,9][i],[3,4,5,5,6],[4,5,6,7,8]),principle:"Nível é contexto para decisão, não uma regra cega.",correct:"Usar ROI, volume e consistência para definir o próximo passo.",alternatives:["Escalar toda campanha acima de ROI 2.","Pausar toda campanha abaixo de ROI 3.","Ignorar volume e olhar apenas CPA."],explanations:["ROI alto com duas vendas não tem o mesmo peso que ROI alto com volume consistente.","Cortes automáticos ignoram margem, estágio e qualidade do tráfego.","CPA isolado também não explica escala.","A classificação correta combina retorno, volume e consistência."] ,tags:["N0","N1","N2","N3"]},
{category:"Criativo",level:14,difficulty:"HARD",title:"Novo não significa diferente",context:"Você recebeu orçamento para produzir cinco novas peças. O time quer apenas trocar cor, música e fonte. Isso não cria cinco hipóteses relevantes.",product:"Curso de tráfego",offer:"R$ {t}",build:i=>metric([67,97,147,197,297][i],[70,95,120,155,210][i],[15000,19000,23000,28000,33000][i],[190,228,276,315,356][i],[24,28,33,39,45][i],[18,22,26,31,35][i],[5,6,7,8,9][i],[4,5,5,6,7],[5,6,7,8,9]),principle:"Um novo teste deve mudar uma hipótese relevante.",correct:"Variar hook, ângulo, roteiro, formato ou personagem.",alternatives:["Trocar somente música e cor.","Duplicar o mesmo vídeo cinco vezes.","Mudar tudo ao mesmo tempo sem registrar hipótese."],explanations:["Alterações cosméticas dificultam aprender o que realmente mudou.","Duplicação não amplia a exploração de hipóteses.","Se tudo muda, você não sabe qual variável produziu o efeito.","Variações relevantes permitem comparar hipóteses."] ,tags:["criativos","hipótese","volume"]},
{category:"Funil",level:8,difficulty:"HARD",title:"Ache o vazamento",context:"O funil tem impressões, cliques, checkout e Pix. O jogador precisa localizar a etapa que está abaixo do esperado sem culpar a última venda.",product:"Workshop de carreira",offer:"R$ {t}",build:i=>metric([37.9,67,97,147,197][i],[35,54,77,104,140][i],[10000,12000,15000,18000,22000][i],[210,240,270,310,340][i],[5,7,10,12,15][i],[4,6,9,10,13][i],[2,2,3,3,4][i],[2,3,3,4,4],[3,4,5,6,7]),principle:"Diagnóstico segue o caminho do dinheiro.",correct:"Comparar taxas entre cada etapa antes de mudar tráfego.",alternatives:["Trocar anúncio imediatamente.","Aumentar orçamento para compensar.","Mudar preço sem olhar o funil."],explanations:["Você pulou a etapa de localizar o vazamento.","Volume maior não conserta uma taxa quebrada.","Preço pode ser causa, mas precisa ser relacionado à etapa.","A leitura por etapas mostra onde a queda é desproporcional."] ,tags:["funnel","leak","diagnóstico"]},
{category:"Oferta",level:17,difficulty:"EXPERT",title:"Produto bom, oferta ruim",context:"Quem compra avalia bem o produto, mas a página não consegue converter visitantes em compradores. A entrega não parece ser o problema.",product:"Curso de finanças pessoais",offer:"R$ {t} sem mecanismo claro",build:i=>metric([67,97,147,197,297][i],[80,110,150,190,240][i],[14000,17000,21000,25000,30000][i],[260,300,350,400,450][i],[8,10,12,14,16][i],[6,8,10,12,14][i],[2,2,3,3,4][i],[4,5,6,6,7],[6,7,8,9,10]),principle:"Produto bom não compensa uma proposta mal comunicada.",correct:"Reestruturar oferta e mensagem antes de escalar tráfego.",alternatives:["Aumentar o orçamento.","Produzir mais tráfego frio.","Trocar apenas o botão da página."],explanations:["Você tentou resolver percepção de valor com volume.","Mais visitas ampliam o mesmo problema.","Um detalhe de botão não explica sozinho a proposta fraca.","A oferta precisa tornar valor, mecanismo, prova e risco compreensíveis."] ,tags:["oferta","valor","mecanismo"]},
{category:"Oferta",level:18,difficulty:"EXPERT",title:"Oferta boa, criativo ruim",context:"Quando o tráfego é qualificado, a página converte bem. O problema aparece antes: poucos cliques chegam da mídia.",product:"Mentoria de anúncios",offer:"R$ {t} com mecanismo claro",build:i=>metric([97,147,197,297,497][i],[75,110,145,190,250][i],[18000,22000,27000,33000,39000][i],[180,205,225,250,280][i],[24,30,36,43,50][i],[19,24,29,35,42][i],[8,10,11,13,15][i],[4,5,6,6,7],[5,6,7,8,9]),principle:"Uma oferta pode estar saudável enquanto o criativo falha.",correct:"Investir em hooks e ângulos para gerar atenção qualificada.",alternatives:["Reduzir o preço.","Trocar o checkout.","Duplicar o orçamento do criativo atual."],explanations:["Preço não é a primeira evidência quando quem chega converte bem.","Checkout não explica falta de cliques.","Duplicar verba não cria demanda.","A evidência aponta para aquisição: melhorar a entrada do funil."] ,tags:["hook","ângulo","oferta"]},
{category:"Caixa",level:10,difficulty:"HARD",title:"Caixa pequeno muda a estratégia",context:"Você tem pouco dinheiro e várias hipóteses. Testar tudo ao mesmo tempo pode deixar a operação sem próxima tentativa.",product:"Ebook de carreira",offer:"R$ {t}",build:i=>metric([19.9,37.9,67,97,147][i],[12,20,31,43,58][i],[5000,7000,9000,11000,14000][i],[80,100,120,140,160][i],[6,7,8,9,10][i],[4,5,6,7,8][i],[1,1,1,1,1][i],1,2),principle:"Com caixa curto, o melhor teste é o que preserva a próxima tentativa.",correct:"Escolher uma hipótese de maior informação e limitar perda.",alternatives:["Testar cinco ofertas simultaneamente.","Gastar tudo para acelerar aprendizado.","Parar toda operação sem tentar validar."],explanations:["Você fragmentou caixa e aprendizado.","Acelerar sem limite pode eliminar o próximo teste.","Preservar caixa não significa nunca testar.","Uma hipótese bem escolhida maximiza aprendizado por real."] ,tags:["capital","prioridade","runway"]},
{category:"Recorrência",level:20,difficulty:"EXPERT",title:"A venda inicial não conta toda a história",context:"A oferta tem compra inicial, order bump e recorrência. Você precisa avaliar valor econômico sem confundir faturamento imediato com lucro.",product:"Comunidade de marketing",offer:"Entrada R$ {t} + recorrência",build:i=>metric([47,67,97,147,197][i],[90,130,170,220,280][i],[12000,16000,20000,25000,30000][i],[190,230,280,330,380][i],[25,31,37,44,51][i],[19,24,29,35,41][i],[6,8,10,12,14][i],[5,6,7,8,9],[6,7,8,9,10]),principle:"Avalie a operação pelo valor e pelos custos do conjunto.",correct:"Separar aquisição, compra inicial, bump e retenção para medir margem.",alternatives:["Escalar só porque o faturamento inicial subiu.","Ignorar recorrência porque é dinheiro futuro.","Considerar todo upsell como lucro."],explanations:["Faturamento maior pode vir com margem pior.","Recorrência é relevante para economia, mesmo que não seja caixa imediato.","Upsell também tem custo e taxa de aceitação.","A análise precisa separar as fontes de receita e seus custos."] ,tags:["LTV","recorrência","upsell"]}
];

const decisionsFor=(t:Template,i:number):Decision[]=>{
 const tkt=[19.9,37.9,67,97,147][i];
 const good=t.correct.replaceAll("{t}",tkt.toString().replace(".",","));
 const [a,b,c]=t.alternatives.map(x=>x.replaceAll("{t}",tkt.toString().replace(".",",")));
 return [
  {id:"a",label:good,hint:"Comprar evidência antes de aumentar risco.",correct:true,cashDelta:-Math.max(4,Math.round(t.build(i).spend*.12)),xp:t.category==="Métricas"?110:100,explanation:t.explanations[3],principle:t.principle,consequence:"Você gasta pouco para melhorar a próxima leitura em vez de comprar volume cego.",metric:"Diagnóstico"},
  {id:"b",label:a,hint:"Decisão agressiva: observe o risco.",cashDelta:-Math.max(12,Math.round(t.build(i).spend*.35)),xp:25,explanation:t.explanations[0],principle:t.principle,consequence:"O caixa cai e você compra mais exposição sem resolver a causa.",metric:"Caixa"},
  {id:"c",label:b,hint:"Procure evidência específica para esta hipótese.",cashDelta:-Math.max(8,Math.round(t.build(i).spend*.2)),xp:25,explanation:t.explanations[1],principle:t.principle,consequence:"Você altera uma variável sem evidência suficiente e reduz a qualidade do aprendizado.",metric:"Leitura"},
  {id:"d",label:c,hint:"Pergunte: qual etapa sustenta esta decisão?",cashDelta:-Math.max(7,Math.round(t.build(i).spend*.16)),xp:20,explanation:t.explanations[2],principle:t.principle,consequence:"A decisão consome caixa e deixa o gargalo original intacto.",metric:"Diagnóstico"}
 ];
};

export const scenarios:Scenario[] = templates.flatMap((t,ti)=>Array.from({length:5},(_,i)=>{
 const m=t.build(i);
 return {
  id:`lvl-${t.level}-${String(ti+1).padStart(2,"0")}-${i+1}`,level:t.level,difficulty:t.difficulty,category:t.category,
  title:t.title,context:t.context,product:t.product,offer:t.offer.replace("{t}",[19.9,37.9,67,97,147][i].toString().replace(".",",")),
  metrics:m,available:["produto","oferta","ticket","gasto","impressões","cliques","CTR","CPC","checkout","Pix","Pix pago","vendas","CPA","ROI","dias de campanha","quantidade de criativos"],
  hidden:i%2===0?["qualidade percebida da oferta","histórico de ontem"]:["motivo do abandono","variação do criativo anterior"],
  decisions:decisionsFor(t,i),principle:t.principle,xp:t.level>=17?150:90,
  caseNote:ti%3===0?"Caso inspirado em padrões de operação real; números adaptados para treinamento.":undefined,tags:t.tags
 };
}));

export const scenariosByLevel=(level:number)=>scenarios.filter(s=>s.level===level);
export const scenariosByCategory=(category:ScenarioCategory)=>scenarios.filter(s=>s.category===category);
export const difficultyLabel=(d:Difficulty)=>({EASY:"FÁCIL",NORMAL:"NORMAL",HARD:"DIFÍCIL",EXPERT:"EXPERT",NIGHTMARE:"NIGHTMARE"}[d]);
export const levelNames=[
 "Aprendizado de economia","Leitura de métricas","Diagnóstico de entrega","Caça ao gargalo","Oferta",
 "Criativos","Primeiro teste","Corte","Diagnóstico","Funil","Pré-escala","Nivelamento","Escala",
 "Criativos em volume","Checkout","Pix","Oferta ruim","Oferta boa + criativo ruim","Escala com caixa","Operação completa"
];
