import {useEffect,useState,type ReactNode} from "react";
import {createFileRoute} from "@tanstack/react-router";
import {ArrowRight,BarChart3,Brain,Check,Flame,RotateCcw,Target,Trophy,Wallet,X,Zap} from "lucide-react";
import {questions,categories,type Category,type Difficulty} from "../game/questions";
export const Route=createFileRoute("/")({component:Index});
type P={xp:number;answered:number;correct:number;streak:number;best:number;cats:Record<string,number>};
const blank:P={xp:0,answered:0,correct:0,streak:0,best:0,cats:{}};
const rank=(x:number)=>x>=1800?"Aristocrata":x>=1000?"Estrategista":x>=450?"Operador":"Aprendiz";
const shuffle=<T,>(a:T[])=>[...a].sort(()=>Math.random()-.5);
function Index(){
 const[p,setP]=useState<P>(blank),[screen,setScreen]=useState<"home"|"play"|"sim">("home"),[qs,setQs]=useState(questions.slice(0,10)),[at,setAt]=useState(0),[pick,setPick]=useState<number|null>(null);
 const initialSim={day:1,cash:600,spend:0,sales:0,revenue:0,profit:0,budget:80,price:150,ctr:0.018,cpm:28,pageCv:0.105,checkoutCv:0.32,fatigue:0,offer:72,traffic:70,creative:68,checkout:76,learning:0,lastAction:"Comece escolhendo como validar sua primeira campanha.",logs:["DIA 1 · Você recebe R$600. Seu objetivo não é gastar tudo: é descobrir uma operação que merece escala."]}; const[sim,setSim]=useState(initialSim);
 useEffect(()=>{try{setP({...blank,...JSON.parse(localStorage.getItem("jdi-progress")||"{}")})}catch{}},[]);
 useEffect(()=>{localStorage.setItem("jdi-progress",JSON.stringify(p))},[p]);
 const start=(d:Difficulty|"Todas")=>{const pool=d==="Todas"?questions:questions.filter(q=>q.difficulty===d);const prepared=shuffle(pool).slice(0,10).map(q=>{const opts=q.options.map((text,index)=>({text,index})).sort(()=>Math.random()-.5);return {...q,options:opts.map(o=>o.text),correct:opts.findIndex(o=>o.index===q.correct)}});setQs(prepared);setAt(0);setPick(null);setScreen("play")};
 const q=qs[at];
 const answer=(i:number)=>{if(pick!==null)return;setPick(i);const ok=i===q.correct;setP(s=>({...s,xp:s.xp+(ok?100:25),answered:s.answered+1,correct:s.correct+(ok?1:0),streak:ok?s.streak+1:0,best:ok?Math.max(s.best,s.streak+1):s.best,cats:{...s.cats,[q.category]:(s.cats[q.category]||0)+(ok?1:0)}}))};
 const reset=()=>{if(confirm("Apagar todo o progresso?")){setP(blank);localStorage.removeItem("jdi-progress")}};
 if(screen==="play")return <Shell p={p} home={()=>setScreen("home")}><main className="play"><div className="playbar"><button onClick={()=>setScreen("home")}>← sair</button><span>{at+1} / {qs.length}</span><span>{q.category} · {q.difficulty}</span></div><article className="question"><label>{q.category.toUpperCase()}</label><h1>{q.title}</h1><p className="context">{q.context}</p><div className="options">{q.options.map((o,i)=>{const st=pick===null?"":i===q.correct?"ok":i===pick?"bad":"";return <button className={"option "+st} disabled={pick!==null} onClick={()=>answer(i)} key={o}><b>{String.fromCharCode(65+i)}</b>{o}{st==="ok"?<Check/>:st==="bad"?<X/>:null}</button>})}</div>{pick!==null&&<div className={"feedback "+(pick===q.correct?"good":"wrong")}><div><b>{pick===q.correct?"Boa decisão.":"Decisão errada."}</b><p>{q.explanation}</p><small><strong>{q.keyNumber}</strong> · {q.nextStep}</small></div><button onClick={()=>{if(at===qs.length-1)setScreen("home");else{setAt(x=>x+1);setPick(null)}}}>{at===qs.length-1?"Finalizar":"Próxima"} <ArrowRight size={16}/></button></div>}</article></main></Shell>;
 if(screen==="sim")return <Shell p={p} home={()=>setScreen("home")}><Simulation sim={sim} setSim={setSim}/></Shell>;
 return <Shell p={p} home={()=>setScreen("home")}><main className="home"><section className="hero"><label>SIMULADOR DE OPERAÇÃO</label><h1>Aprenda a pensar<br/><em>como operador.</em></h1><p>Decida sob pressão, proteja o caixa, encontre gargalos e prove uma oferta antes de escalar.</p><div className="actions"><button className="primary" onClick={()=>start("Todas")}>Começar treino <ArrowRight size={17}/></button><button className="secondary" onClick={()=>setScreen("sim")}><Wallet size={17}/> Simular R$600</button></div></section><section className="metrics"><Metric icon={<Zap/>} label="XP" value={p.xp.toLocaleString("pt-BR")} sub={rank(p.xp)}/><Metric icon={<Target/>} label="Precisão" value={p.answered?Math.round(p.correct/p.answered*100)+"%":"—"} sub={p.answered+" decisões"}/><Metric icon={<Flame/>} label="Sequência" value={String(p.streak)} sub={"recorde "+p.best}/><Metric icon={<Trophy/>} label="Nível" value={rank(p.xp)} sub="progressão"/></section><div className="section"><div><label>MODOS</label><h2>Escolha seu campo.</h2></div></div><section className="modes"><Mode icon={<Brain/>}tag="APRENDER"title="Modo Treino"desc="10 decisões com feedback imediato." on={()=>start("Todas")}/><Mode icon={<Target/>}tag="DECIDIR"title="Modo Operador"desc="Casos mais próximos de uma operação real." on={()=>start("Operador")}/><Mode icon={<BarChart3/>}tag="PENSAR"title="Modo Estrategista"desc="Diagnóstico, validação e escala." on={()=>start("Estrategista")}/><Mode icon={<Wallet/>}tag="SIMULAR"title="Modo R$600"desc="Sobreviva 7 dias sem quebrar o caixa." on={()=>setScreen("sim")}/></section><div className="section"><label>COMPETÊNCIAS</label><h2>Seu mapa de operador.</h2></div><section className="skills">{categories.map(c=><Skill key={c} name={c} value={p.cats[c]||0}/>)}</section><div className="rules"><span>REGRA DO JOGO</span><b>Oferta primeiro.</b><b>Caixa antes de tráfego.</b><b>Diagnóstico antes de mudança.</b><b>Validação antes de escala.</b></div><button className="reset" onClick={reset}><RotateCcw size={14}/> Resetar progresso</button></main></Shell>
}
function Shell({children,p,home}:{children:ReactNode;p:P;home:()=>void}){return <div className="app"><header><button className="brand" onClick={home}><strong>JI</strong><span>Jogo do Info<small>OPERATOR SIM</small></span></button><div className="rank">{rank(p.xp)} <b>{p.xp} XP</b></div></header>{children}<footer>JOGO DO INFO · aprenda com decisões, não com teoria.</footer></div>}
function Metric({icon,label,value,sub}:{icon:ReactNode;label:string;value:string;sub:string}){return <div className="metric"><i>{icon}</i><small>{label}</small><b>{value}</b><span>{sub}</span></div>}
function Mode({icon,tag,title,desc,on}:{icon:ReactNode;tag:string;title:string;desc:string;on:()=>void}){return <button className="mode" onClick={on}><i>{icon}</i><label>{tag}</label><h3>{title}</h3><p>{desc}</p><ArrowRight/></button>}
function Skill({name,value}:{name:Category;value:number}){return <div className="skill"><div><b>{name}</b><span>{value} acertos</span></div><div className="skillbar"><i style={{width:Math.min(100,value*20)+"%"}}/></div></div>}
function Simulation({sim,setSim}:{sim:any;setSim:any}){
 const derive=(s:any)=>{
  const spend=Math.min(s.budget,s.cash);
  const impressions=Math.round(spend/Math.max(1,s.cpm)*1000);
  const clicks=Math.round(impressions*s.ctr);
  const checkouts=Math.round(clicks*(s.pageCv*(s.traffic/100)));
  const expected=Math.max(0,checkouts*(s.checkoutCv*(s.checkout/100))*(1-s.fatigue*.012));
  const noise=[.84,1.08,.92,1.16,.96,.88,1.04][s.day-1]||1;
  const sales=Math.max(0,Math.round(expected*noise));
  const revenue=sales*s.price;
  const profit=revenue-spend;
  const cpc=clicks?spend/clicks:0, cpa=sales?spend/sales:0, roi=spend?revenue/spend:0;
  return {spend,impressions,clicks,checkouts,sales,revenue,profit,cpc,cpa,roi};
 };
 const m=derive(sim);
 const choose=(action:string)=>{
  setSim((s:any)=>{
   const d=derive(s); let n={...s}; let message="";
   if(action==="hold"){n.budget=Math.max(35,Math.round(s.budget*.9));n.fatigue=Math.min(12,s.fatigue+1);n.learning+=8;message="Você segurou o orçamento para comprar mais dados. A campanha envelheceu um pouco."}
   if(action==="scale"){n.budget=Math.min(180,Math.round(s.budget*1.3));n.fatigue=Math.min(12,s.fatigue+2);n.learning+=3;message="Você aumentou o orçamento. Se o gargalo continuar, agora você só compra mais tráfego para o mesmo problema."}
   if(action==="creative"){n.ctr=Math.min(.032,s.ctr+.004);n.creative=Math.min(100,s.creative+9);n.fatigue=Math.max(0,s.fatigue-5);n.budget=Math.max(45,Math.round(s.budget*.95));n.learning+=14;message="Você renovou o criativo. O CTR melhora e a fadiga cai, mas o orçamento não foi escalado antes de provar o novo ângulo."}
   if(action==="offer"){n.offer=Math.min(100,s.offer+10);n.price=s.price===150?159:165;n.pageCv=Math.min(.15,s.pageCv+.015);n.budget=Math.max(45,Math.round(s.budget*.95));n.learning+=16;message="Você trabalhou a oferta. A promessa ficou mais clara e a conversão da página ganhou força."}
   if(action==="checkout"){n.checkout=Math.min(100,s.checkout+12);n.checkoutCv=Math.min(.48,s.checkoutCv+.035);n.budget=Math.max(45,Math.round(s.budget*.95));n.learning+=16;message="Você atacou o checkout. Menos compradores abandonam depois de clicar em comprar."}
   if(action==="traffic"){n.traffic=Math.min(100,s.traffic+12);n.cpm=Math.max(20,s.cpm-2);n.ctr=Math.max(.012,s.ctr-.001);n.budget=Math.max(45,Math.round(s.budget*.95));n.learning+=10;message="Você refinou o tráfego. A qualidade sobe e o CPM cai, mas o criativo perde um pouco de força."}
   if(action==="cut"){n.budget=Math.max(30,Math.round(s.budget*.65));n.fatigue=Math.max(0,s.fatigue-2);n.learning+=5;message="Você cortou exposição. Isso protege caixa, mas também reduz a velocidade de aprendizado."}
   const current=derive(n); const nextCash=s.cash-current.spend+current.revenue; 
   n.cash=Math.round(nextCash*100)/100;n.spend=s.spend+current.spend;n.revenue=s.revenue+current.revenue;n.sales=s.sales+current.sales;n.profit=s.profit+current.profit;
   n.lastAction=message;n.logs=[`DIA ${s.day} · ${action.toUpperCase()} · ${current.sales} venda(s), R$ ${Math.round(current.revenue)} receita, R$ ${Math.round(current.spend)} gasto.`,message,...s.logs].slice(0,7);
   n.day=s.day+1; return n;
  });
 };
 if(sim.day>7)return <main className="play"><article className="result"><label>FIM DA SIMULAÇÃO</label><h1>7 dias. <em>O caixa fala.</em></h1><p className="resultintro">Você não venceu por ter gasto mais. Venceu se descobriu onde estava o gargalo e terminou com uma operação mais saudável.</p><div className="metrics"><Metric icon={<Wallet/>}label="Caixa final"value={`R$ ${sim.cash.toFixed(0)}`}sub="saldo"/><Metric icon={<BarChart3/>}label="Lucro"value={`R$ ${sim.profit.toFixed(0)}`}sub="receita − tráfego"/><Metric icon={<Target/>}label="ROI acumulado"value={sim.spend?`${(sim.revenue/sim.spend).toFixed(1)}x`:"—"}sub="retorno sobre mídia"/><Metric icon={<Flame/>}label="Vendas"value={String(sim.sales)}sub="total"/></div><div className="resultbox"><b>Aprendizado operacional</b><strong>{sim.learning} pts</strong><span>{sim.learning>=80?"Você diagnosticou e melhorou a operação.":sim.learning>=50?"Você encontrou alguns gargalos, mas ainda deixou dinheiro na mesa.":"Você tomou decisões rápidas demais sem comprar evidência suficiente."}</span></div><button className="primary" onClick={()=>setSim(initialSim)}>Jogar novamente <RotateCcw size={16}/></button></article></main>;
 return <main className="sim"><div className="playbar"><button onClick={()=>setSim((s:any)=>({...s,day:8}))}>← sair</button><span>DIA {sim.day} / 7</span><span>OPERAÇÃO · R$600</span></div>
 <div className="simtop"><div><label>DIA {sim.day} · PAINEL DO OPERADOR</label><h1>Não olhe só para <em>vendas.</em></h1><p>{sim.lastAction}</p></div><div className="cashbox"><small>CAIXA DISPONÍVEL</small><b>R$ {sim.cash.toFixed(0)}</b><span>Orçamento amanhã · R$ {sim.budget}</span></div></div>
 <div className="kpis"><Metric icon={<Wallet/>}label="Gasto hoje"value={`R$ ${m.spend}`}sub={`de R$ ${sim.budget} planejados`}/><Metric icon={<BarChart3/>}label="Receita"value={`R$ ${m.revenue}`}sub={`${m.sales} venda(s)`}/><Metric icon={<Target/>}label="CPA"value={m.sales?`R$ ${m.cpa.toFixed(0)}`:"—"}sub="custo por venda"/><Metric icon={<Zap/>}label="ROI"value={m.spend?`${m.roi.toFixed(1)}x`:"—"}sub="receita ÷ gasto"/></div>
 <section className="operator-grid"><div>
  <div className="panel"><div className="paneltitle"><span>FUNIL DA CAMPANHA</span><small>{m.impressions.toLocaleString("pt-BR")} impressões</small></div><div className="funnel"><Funnel label="Impressões"value={m.impressions.toLocaleString("pt-BR")} rate="100%"/><Funnel label="Cliques"value={m.clicks.toString()} rate={sim.ctr*100+"% CTR"}/><Funnel label="Checkout"value={m.checkouts.toString()} rate={(sim.pageCv*sim.traffic)+"% pós-clique"}/><Funnel label="Vendas"value={m.sales.toString()} rate={(sim.checkoutCv*sim.checkout)+"% checkout"}/></div></div>
  <div className="panel"><div className="paneltitle"><span>SAÚDE DA OPERAÇÃO</span><small>o que pode quebrar</small></div><div className="health"><Health name="Criativo / CTR"value={Math.round(sim.creative-sim.fatigue*3)} note={`${(sim.ctr*100).toFixed(1)}% CTR`}/><Health name="Oferta / página"value={Math.round(sim.offer)} note={`${(sim.pageCv*100).toFixed(1)}% conversão`}/><Health name="Checkout"value={Math.round(sim.checkout)} note={`${(sim.checkoutCv*100).toFixed(1)}% conversão`}/><Health name="Tráfego"value={Math.round(sim.traffic)} note={`${sim.cpm} CPM`}/></div></div>
 </div><aside className="decision"><span className="eyebrow">SUA DECISÃO · DIA {sim.day}</span><h2>Qual é o problema mais importante agora?</h2><p>Leia o funil antes de mexer no orçamento. Uma decisão errada hoje altera as métricas de amanhã.</p><div className="diagnosis"><b>Leitura rápida</b><span>{m.sales===0&&m.clicks>0?"Existe tráfego, mas ainda não houve venda.":m.cpa>sim.price?"Você está pagando mais por venda do que recebe por ela.":sim.ctr<.016?"O anúncio está fraco para gerar cliques.":sim.checkout<65?"O vazamento está perto do checkout.":"A operação está saudável o bastante para testar crescimento."}</span></div><button className="decisionbtn" onClick={()=>choose("creative")}><b>Renovar criativo</b><small>CTR baixo ou fadiga alta · ↓ fadiga</small></button><button className="decisionbtn" onClick={()=>choose("offer")}><b>Melhorar oferta</b><small>Promessa/conversão da página · ↑ CVR</small></button><button className="decisionbtn" onClick={()=>choose("checkout")}><b>Corrigir checkout</b><small>Abandono pós-clique · ↑ compras</small></button><button className="decisionbtn" onClick={()=>choose("traffic")}><b>Refinar tráfego</b><small>Qualidade/CPM · ↓ custo</small></button><button className="decisionbtn" onClick={()=>choose("scale")}><b>Escalar +30%</b><small>Só se o funil já estiver saudável</small></button><button className="decisionbtn muted" onClick={()=>choose("hold")}><b>Manter e coletar dados</b><small>Não mudar tudo ao mesmo tempo</small></button><button className="decisionbtn danger" onClick={()=>choose("cut")}><b>Cortar orçamento</b><small>Priorizar sobrevivência do caixa</small></button></aside></section>
 <section className="panel logpanel"><div className="paneltitle"><span>DIÁRIO DE OPERAÇÃO</span><small>suas decisões deixam rastros</small></div>{sim.logs.map((x:string,i:number)=><p key={i}>{x}</p>)}</section></main>
}
function Funnel({label,value,rate}:{label:string;value:string;rate:string}){return <div className="funnelrow"><span>{label}</span><b>{value}</b><small>{rate}</small></div>}
function Health({name,value,note}:{name:string;value:number;note:string}){return <div className="healthrow"><span>{name}</span><div><i style={{width:Math.max(5,Math.min(100,value))+"%"}}/></div><small>{note}</small></div>
}
